# Generated by Django 4.2.7 on 2024-01-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('bulder', models.CharField(help_text='0 - droga, 1 - bulder, 2 - inne', max_length=1)),
                ('opis', models.TextField(default='uzupełnij', help_text='tutaj wpisz dłuższy opis miejsca')),
                ('wyceny', models.CharField(choices=[('bd', 'uzupełnij'), ('łatwe', 'Łatwe'), ('średnie', 'Średnie'), ('trudne', 'Trudne'), ('zróżnicowane', 'Zróżnicowane')], default='bd', max_length=15)),
                ('skala', models.CharField(default='uzupełnij', help_text='pojedyncza nazwa - np. piaskowiec, granit, wapień', max_length=100)),
                ('wysokosc', models.DecimalField(decimal_places=0, help_text='podaj bez przcecinków przybliżoną wysokość', max_digits=3, null=True)),
                ('ilość_dróg', models.CharField(choices=[('bd', 'uzupełnij'), ('mały', '<20'), ('średni', '20-100'), ('duży', '>100')], default='bd', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Topo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_topo', models.CharField(help_text='Nazwa która będzie wyświetlała się w popupie', max_length=100)),
                ('autor', models.CharField(max_length=200)),
                ('crags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.crag')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_strony', models.CharField(help_text='Nazwa która będzie wyświetlała się w popupie', max_length=100)),
                ('link', models.URLField()),
                ('ocena', models.CharField(help_text='skala od 1 do 5', max_length=1)),
                ('crags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.crag')),
            ],
            options={
                'ordering': ['-crags'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_filmu', models.CharField(help_text='Nazwa która będzie wyświetlała się w popupie', max_length=100)),
                ('link', models.URLField()),
                ('crags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.crag')),
            ],
            options={
                'ordering': ['-crags'],
            },
        ),
    ]
