# Generated by Django 4.2.7 on 2024-01-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={},
        ),
        migrations.RemoveField(
            model_name='crag',
            name='bulder',
        ),
        migrations.AddField(
            model_name='crag',
            name='rodzaj',
            field=models.CharField(choices=[('Bulder', 'bulder'), ('Sport', 'drogi ubezpieczone'), ('Trad', 'własna asekuracja'), ('Scianka', 'ścianka wspinaczkowa'), ('Brak danych', 'brak danych')], default='Brak danych', max_length=100),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_drogi', models.CharField(default='brak', max_length=200)),
                ('rejon', models.ForeignKey(default='brak', null=True, on_delete=django.db.models.deletion.CASCADE, to='map.crag')),
            ],
        ),
    ]
