# Generated by Django 4.2.7 on 2024-01-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_movie_options_alter_site_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
