# Generated by Django 4.2.7 on 2023-12-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_crags_delete_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crags',
            old_name='Nazwa',
            new_name='nazwa',
        ),
        migrations.AlterField(
            model_name='crags',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='crags',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
