# Generated by Django 4.2.7 on 2024-01-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_delete_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crag',
            old_name='ilość_dróg',
            new_name='ilosc_drog',
        ),
    ]
