# Generated by Django 4.2.7 on 2023-12-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_rename_nazwa_crags_nazwa_alter_crags_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bulder', models.CharField(help_text='0 - droga, 1 - bulder, 2 - inne', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_strony', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('ocena', models.CharField(help_text='skala od 1 do 5', max_length=1)),
                ('crags', models.ManyToManyField(to='map.crag')),
            ],
        ),
        migrations.DeleteModel(
            name='Crags',
        ),
    ]
