# Generated by Django 4.2.7 on 2024-01-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_ilość_dróg_crag_ilosc_drog'),
    ]

    operations = [
        migrations.AddField(
            model_name='crag',
            name='bulder',
            field=models.CharField(default='Dsds', max_length=100),
        ),
    ]
