# Generated by Django 4.2.7 on 2024-01-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_crag_bulder'),
    ]

    operations = [
        migrations.AddField(
            model_name='crag',
            name='facja',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='crag',
            name='nazwa_alt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='crag',
            name='rejon',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='crag',
            name='rejon_dod',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='crag',
            name='rodzaj_alt',
            field=models.CharField(choices=[('Bulder', 'bulder'), ('Sport', 'drogi ubezpieczone'), ('Trad', 'własna asekuracja'), ('Scianka', 'ścianka wspinaczkowa'), ('Brak danych', 'brak danych')], default='Brak danych', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crag',
            name='wiek_skal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='crag',
            name='ilosc_drog',
            field=models.CharField(choices=[('Brak danych', 'brak danych'), ('Mała', '<25'), ('Średnia', '25-100'), ('Duża', '>100')], default='Brak danych', max_length=15),
        ),
        migrations.AlterField(
            model_name='crag',
            name='opis',
            field=models.TextField(default='uzupełnij', help_text='tutaj wpisz dłuższy opis miejsca', max_length=1000),
        ),
        migrations.AlterField(
            model_name='crag',
            name='rodzaj',
            field=models.CharField(choices=[('Bulder', 'bulder'), ('Sport', 'drogi ubezpieczone'), ('Trad', 'własna asekuracja'), ('Scianka', 'ścianka wspinaczkowa'), ('Brak danych', 'brak danych')], default='Brak danych', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crag',
            name='skala',
            field=models.CharField(default='uzupełnij', help_text='pojedyncza nazwa - np. piaskowiec, granit, wapień', max_length=30),
        ),
        migrations.AlterField(
            model_name='crag',
            name='wyceny',
            field=models.CharField(choices=[('Brak danych', 'brak danych'), ('Łatwe', 'łatwe'), ('Średnie', 'średnie'), ('Trudne', 'trudne'), ('Zróżnicowane', 'zróżnicowane')], default='bd', max_length=15),
        ),
    ]
