# Generated by Django 4.2.7 on 2023-12-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_remove_site_crags_site_crags'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='nazwa_miejsca',
            field=models.CharField(default=0, help_text='Nazwa miejsca, tożsama z Crags/Nazwa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='nazwa_strony',
            field=models.CharField(help_text='Nazwa która będzie wyświetlała się w popupie', max_length=100),
        ),
    ]
