# Generated by Django 4.2.7 on 2024-01-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_crag_facja_crag_nazwa_alt_crag_rejon_crag_rejon_dod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crag',
            name='bulder',
        ),
        migrations.AlterField(
            model_name='crag',
            name='facja',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='crag',
            name='ilosc_drog',
            field=models.CharField(choices=[('Brak danych', 'brak danych'), ('<25', '<25'), ('25-100', '25-100'), ('>100', '>100')], default='Brak danych', max_length=15),
        ),
        migrations.AlterField(
            model_name='crag',
            name='nazwa_alt',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='crag',
            name='rejon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='crag',
            name='rejon_dod',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='crag',
            name='skala',
            field=models.CharField(choices=[('Wapień', 'wapień'), ('Piaskowiec', 'piaskowiec'), ('Granit', 'granit'), ('Bazalt', 'bazalt'), ('Plastik', 'plastik'), ('Beton', 'beton')], default='bd', max_length=30),
        ),
        migrations.AlterField(
            model_name='crag',
            name='wiek_skal',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
