# Generated by Django 4.2.7 on 2024-02-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_remove_crag_bulder_alter_crag_facja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crag',
            name='nazwa',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='crags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.crag', to_field='nazwa'),
        ),
    ]
