# Generated by Django 4.2.7 on 2024-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_alter_site_crags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='nazwa_strony',
            field=models.CharField(default='bd', help_text='Nazwa która będzie wyświetlała się w popupie', max_length=100),
        ),
    ]
