# Generated by Django 4.2.7 on 2024-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_alter_site_nazwa_strony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crag',
            name='nazwa',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
