# Generated by Django 4.2.7 on 2024-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_alter_crag_nazwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topo',
            name='crags',
        ),
        migrations.AddField(
            model_name='topo',
            name='crags',
            field=models.ManyToManyField(to='map.crag'),
        ),
    ]
