# Generated by Django 4.2.7 on 2024-02-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_remove_topo_crags_topo_crags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='crags',
        ),
        migrations.RemoveField(
            model_name='site',
            name='link',
        ),
        migrations.RemoveField(
            model_name='site',
            name='nazwa_strony',
        ),
        migrations.RemoveField(
            model_name='site',
            name='ocena',
        ),
        migrations.AddField(
            model_name='site',
            name='data',
            field=models.CharField(default='', help_text='wpisz numer daty powstania linku jesli znasz', max_length=4),
        ),
        migrations.AddField(
            model_name='site',
            name='polecane',
            field=models.BooleanField(default=False, verbose_name='zaznacz jesli polecana strona'),
        ),
        migrations.AddField(
            model_name='site',
            name='rodzaj_strony',
            field=models.CharField(choices=[('topo', 'topo'), ('info', 'info'), ('artykuł', 'artykuł'), ('artykuł naukowy', 'artykuł naukowy'), ('blog', 'blog')], default='inne', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='strona',
            field=models.CharField(choices=[('27crags.com', '27crags.com'), ('wpinka.org', 'wpinka.org'), ('8a.nu', '8a.nu'), ('buldering.pl', 'buldering.pl'), ('wikipedia.org', 'wikipedia.org'), ('thecrag.com', 'thecrag.com'), ('goryonline.com', 'goryonline.com'), ('portalgorski.pl', 'portalgorski.pl'), ('inne', 'inne')], default='inne', help_text='wybierz jeśli jest na liście', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='tytul',
            field=models.CharField(default='inne', help_text='Nazwa która będzie wyświetlała się w popupie', max_length=100),
        ),
        migrations.AddField(
            model_name='topo',
            name='link',
            field=models.URLField(default='google.com'),
        ),
    ]
