# Generated by Django 4.2.7 on 2024-02-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_remove_site_crags_remove_site_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topo',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
