# Generated by Django 4.2.7 on 2024-02-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_alter_topo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='link',
            field=models.URLField(default='', max_length=300),
        ),
    ]
