# Generated by Django 4.2.7 on 2024-02-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_site_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='crags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.crag'),
        ),
    ]
